### ISSUE TITLE
Sorting breaks Sass expressions

### ISSUE THREAD

**Issue by okonet** [wildbit/postcss-sorting-config-wildbit#1]
``` scss
@each $customer, $width in $customers {
  .customer-logo_#{$customer} {
    width: $width;
    background-position: ($customer-position * -1) 0;
  }
  $customer-position: $customer-position + $width + 5px;
}
```

becomes

``` scss
@each $customer, $width in $customers {
  $customer-position: $customer-position + $width + 5px;
  .customer-logo_#{$customer} {
    width: $width;
    background-position: ($customer-position * -1) 0;
  }
}
```

which is wrong.
